version: '3'

services:
  website:
    tty: true
    build: ./web
    container_name: website
    ports:
      - '3000:3000'
    volumes:
      - './web/:/usr/src/web'
      - /usr/src/web/node_modules/
    depends_on:
      - server
      - database
  server:
    build: ./server
    container_name: server
    environment:
      - DB_USER=root
      - DB_PWD=root
    ports:
      - '3020:3020'
    volumes:
      - './server/:/usr/src/server'
      - /usr/src/server/node_modules/
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=movies